### ISSUE TITLE
MESSAGE_STATUS_CONSOLE_BLUE 

### ISSUE THREAD

**Issue by Diego-OT** [SaiyansKing/optimized_forgottenserver#25]
https://github.com/SaiyansKing/optimized_forgottenserver/blob/21d7059a31bf74490846ca533d1d06a79c19aaa6/src/protocolgame.cpp#L5759

The blue message is not appearing on the client, it seems they removed/changed that value

player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "test")

**Comment by joseluis2g** [comment]
I can guess new client removed this color chat messages.

**Comment by SaiyansKing** [comment]
Depends how you look at it, there never were those message types, you could use them because there was a bug in the old c code they wrote. If you think about it there's a reason why even after cipsoft added server log they still appeared on default channel, that is because they were never accounted by cipsoft as they were simple "bug".

MESSAGE_STATUS_CONSOLE_BLUE, MESSAGE_STATUS_CONSOLE_RED, MESSAGE_EVENT_ORANGE, MESSAGE_STATUS_CONSOLE_ORANGE used to have their colors because they have their talktype counter-parts.
In the new implementation they are separated so those types are color-less and that's why they don't appear on default or even server-log anymore.
