### ISSUE TITLE
Staticdata Output

### ISSUE THREAD

**Issue by Diego-OT** [SaiyansKing/optimized_forgottenserver#32]
I noticed here, that some old achievements are missing in staticdata.txt
like "Allowance Collector", "Askarak Nemesis" and few others

**Comment by SaiyansKing** [comment]
Are you serious right now? You must be completely stupid as a game developer to add achievements that are https://tibiopedia.pl/images/static/achievements/secret.gif to your game files where everyone simple can see them(unless it is single-player game).

ps. there might be a lot of old secret achievements that are still unknown because they can need to do something stupid no-one yet did.

**Comment by Diego-OT** [comment]
I didn't know that all of those without ID were secret, per example "Bunny Slipped" as tfs default, it is not configured correctly https://github.com/otland/forgottenserver/blob/master/data/lib/core/achievements.lua#L207
I did the function that shows the achievements on the client, now I'm in doubt what to send instead of the achiev~ ID, maybe I should send a boolean, I will test
But thanks for clarifying.
